version: '3'
services:
  mystrapiDB:
    container_name: mystrapiDB
    platform: ${DB_PLATFORM_VERSION} #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: ${DB_IMAGE_VERSION}  #for platform warning on Apple M1 chips
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - mystrapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'

volumes:
  mystrapi-data:
